# Generated by Django 4.2 on 2023-04-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='synopsis',
            field=models.TextField(default='desc', max_length=500),
            preserve_default=False,
        ),
    ]
