# Generated by Django 4.2 on 2023-04-22 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='numofpages',
            field=models.IntegerField(verbose_name='Number of Pages'),
        ),
    ]
